### ISSUE TITLE
Ship visualization

### ISSUE THREAD

**Issue by icarofonseca** [tanguyteulet/FeedBarge#1]
I have checked the source code and confirmed that the visualization does not display the Y position of decks, but it is still used to calculate the weight distribution and CG.

In addition, I noticed that there is a problem with the `fullnessCGMapping` properties in the specification. They only include one CG, but should have at least two: https://observablehq.com/@icarofonseca/object-weight-define-and-calculate-a-tanks-weight-and-cente/3.

**Comment by tanguyteulet** [comment]
OK, so there is no way to display it correctly?

I will modify so that the centres of gravity are correctly coded. 

Thanks for looking at my code.

**Comment by icarofonseca** [comment]
It is not possible. If it is very important we can add this functionality in the future, but it might take longer than Friday.

**Comment by icarofonseca** [comment]
Let me know when you have finished the specification so I can upload it to the library.

**Comment by tanguyteulet** [comment]
I have modified the centre of gravity for all the tanks and I have also removed the decks as the display showed that they were not correctly positioned. The model is now finished. Thanks for your help and for putting the model in the library.

**Comment by icarofonseca** [comment]
Please try to add the specification by yourself:
1. Accept the proposed modifications.
2. Go to the following folder: https://github.com/shiplab/vesseljs/tree/dev/examples/specs/ship_specifications.
3. Select "Add file" on the upper right corner.
4. Upload the modified specification.

**Comment by tanguyteulet** [comment]
I do the modification but I can't upload the modified specification. I don't have the access :
"Uploads are disabled. File uploads require push access to this repository."

**Comment by icarofonseca** [comment]
Ok, thank you for letting me know.

Then I will do it for you.

Ícaro Fonseca
